version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vimemo_development
      POSTGRES_USER: katounaoto
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./back:/app
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://katounaoto:${POSTGRES_PASSWORD}@db:5432/vimemo_development

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    command: yarn dev -p 4000
    ports:
      - "8000:4000"
    tty: true
    stdin_open: true
volumes:
  postgres_data:
  bundle_data:
  node_modules: